gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  
# Site settings
title: Agava Apartments, Balica Rat, Omis, Croatia
email: reservation@klica.net
description: > # this means to ignore newlines until "baseurl:"
  Enjoy your summer near Omiš, Croatia. Agava Apartments.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.klica.net" # the base hostname & protocol for your site

# User setting
author: Elvira Balić
owner: Elvira Balić
email: agava@klica.net

facebook:
 app_id: 
 publisher: 
 admins: 

address:
  - line: "43.416984,16.719161"
  #- line: "Balića Rat"
  #- line: "Stanići, Croatia"
  # Feel free to add more lines here 
telephone: +385915699652
copyright: Agava Apartments

# API settings
google_api_key: AIzaSyAeF6oJkdHb9BA6L-v0Xmvq7sR95QJIZoc

# Build settings
markdown: kramdown

calendar_timezone_offset: 0100 
calendar_csv: calendar.csv

google_site_verification:
