# Site settings
title: Agava Apartments
email: reservation@klica.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Tito Balić
email: reservation@klica.net
facebook_username: omisz
address:
  - line: "43.416984,16.719161"
  #- line: "Balića Rat"
  #- line: "Stanići, Croatia"
  # Feel free to add more lines here 
telephone: +385915699652
copyright: Agava Apartments

# API settings
google_api_key: AIzaSyAeF6oJkdHb9BA6L-v0Xmvq7sR95QJIZoc

# Build settings
markdown: kramdown

calendar_timezone_offset: 0100 
calendar_csv: example/events.csv
calendar_focus_date: 2017-01-06